export const mockApplications = [
  {
    id: 'app_1',
    jobId: '1',
    jobTitle: 'Senior React Developer',
    company: 'TechFlow Corp',
    seekerId: 'seeker_001',
    seekerName: 'Alice Johnson',
    status: 'REVIEWING',
    appliedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'app_2',
    jobId: '2',
    jobTitle: 'Frontend Engineer (Vite, React)',
    company: 'Innovate Labs',
    seekerId: 'seeker_001',
    seekerName: 'Alice Johnson',
    status: 'APPLIED',
    appliedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'app_3',
    jobId: '3',
    jobTitle: 'Junior Web Developer',
    company: 'StartUp Inc',
    seekerId: 'seeker_002',
    seekerName: 'Bob Smith',
    status: 'ACCEPTED',
    appliedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'app_4',
    jobId: '1',
    jobTitle: 'Senior React Developer',
    company: 'TechFlow Corp',
    seekerId: 'seeker_003',
    seekerName: 'Carol White',
    status: 'REJECTED',
    appliedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];
